# Generated by Django 5.1.4 on 2026-06-07 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Current AI-calculated safety score', max_digits=5)),
                ('safety_score_trend', models.CharField(choices=[('up', 'Improving'), ('down', 'Declining'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('total_threats_detected', models.PositiveIntegerField(default=0)),
                ('threats_blocked_this_month', models.PositiveIntegerField(default=0)),
                ('threat_frequency_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Average threats encountered per week', max_digits=5)),
                ('top_scam_categories', models.JSONField(default=list, help_text='Ranked list of scam categories this user encounters most')),
                ('weekly_scan_trend', models.JSONField(default=list, help_text="[{week: 'YYYY-WW', scans: N, threats: N}, ...] for the past 12 weeks")),
                ('monthly_safety_trend', models.JSONField(default=list, help_text="[{month: 'YYYY-MM', safety_score: N}, ...] for the past 6 months")),
                ('recommendations', models.JSONField(default=list, help_text='Personalized safety recommendations from AI analysis')),
                ('personalized_tips', models.JSONField(default=list, help_text="Behavioral safety tips tailored to this user's threat profile")),
                ('risk_profile', models.CharField(choices=[('very_safe', 'Very Safe'), ('safe', 'Safe'), ('moderate', 'Moderate Risk'), ('high_risk', 'High Risk'), ('critical', 'Critical')], default='very_safe', max_length=20)),
                ('scam_categories_breakdown', models.JSONField(default=dict, help_text='Category → count breakdown of all detected scams')),
                ('ai_narrative', models.TextField(blank=True, help_text="Full AI-written safety narrative for the user's weekly report")),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'db_table': 'ai_insights',
            },
        ),
    ]
