# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_insights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['safety_score', 'risk_profile'], name='ai_insights_safety__99b78b_idx'),
        ),
    ]
