# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.contrib.postgres.indexes
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phishing', 'Phishing'), ('financial_fraud', 'Financial / Investment Fraud'), ('lottery_scam', 'Lottery / Prize Scam'), ('romance_scam', 'Romance Scam'), ('tech_support', 'Tech Support Scam'), ('impersonation', 'Government / Bank Impersonation'), ('job_scam', 'Fake Job Offer'), ('upi_fraud', 'UPI / Payment Fraud'), ('malware', 'Malware / Ransomware'), ('social_engineering', 'Social Engineering'), ('fake_ecommerce', 'Fake E-Commerce'), ('cryptocurrency', 'Cryptocurrency Fraud'), ('other', 'Other')], db_index=True, max_length=30)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=2)),
                ('keywords', models.JSONField(default=list, help_text="List of keywords/phrases used for matching (e.g., ['free prize', 'click now'])")),
                ('malicious_urls', models.JSONField(default=list, help_text='List of known malicious URLs or domain patterns')),
                ('malicious_phone_numbers', models.JSONField(default=list, help_text='Reported phone numbers associated with this scam')),
                ('regex_patterns', models.JSONField(default=list, help_text='Regex patterns for advanced text matching')),
                ('source', models.CharField(choices=[('manual', 'Manually Added'), ('ai_detected', 'AI Detected'), ('user_reported', 'User Reported'), ('external_feed', 'External Threat Feed'), ('cert_in', 'CERT-In Advisory'), ('rbi', 'RBI Advisory')], default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('credibility_score', models.DecimalField(decimal_places=3, default=0.5, help_text='Confidence in this threat record (0-1)', max_digits=4)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by security analyst')),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('reported_count', models.PositiveIntegerField(default=0, help_text='Number of times users have encountered this threat')),
                ('ai_metadata', models.JSONField(default=dict, help_text='Additional AI-generated context for this threat')),
            ],
            options={
                'verbose_name': 'Threat',
                'verbose_name_plural': 'Threat Database',
                'db_table': 'threat_database',
                'ordering': ['-severity', '-reported_count'],
                'indexes': [models.Index(fields=['category', 'severity', 'is_active'], name='threat_data_categor_6549f4_idx'), models.Index(fields=['is_active', 'is_verified'], name='threat_data_is_acti_09a052_idx'), django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='idx_threat_keywords_gin'), django.contrib.postgres.indexes.GinIndex(fields=['malicious_urls'], name='idx_threat_urls_gin')],
            },
        ),
    ]
