# Generated by Django 5.1.4 on 2026-06-07 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('name', models.CharField(help_text='Family group display name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='family_avatars/')),
                ('invite_code', models.CharField(db_index=True, help_text='6-12 character unique invite code (case-insensitive)', max_length=12, unique=True)),
                ('invite_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_invite_active', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('average_safety_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('threats_detected', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Family Group',
                'verbose_name_plural': 'Family Groups',
                'db_table': 'family_groups',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('child', 'Child'), ('elderly', 'Elderly'), ('member', 'Member')], default='member', max_length=20)),
                ('permissions', models.JSONField(default=dict, help_text='Fine-grained permission overrides for this member')),
                ('is_active', models.BooleanField(default=True)),
                ('join_method', models.CharField(choices=[('invite_code', 'Invite Code'), ('direct_add', 'Directly Added by Admin'), ('email_invite', 'Email Invitation')], default='invite_code', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_be_monitored', models.BooleanField(default=True, help_text="If True, this member's activity appears on family dashboard")),
                ('alert_parent_on_threat', models.BooleanField(default=True, help_text='If True, parents/guardians are alerted when this member encounters a threat')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'db_table': 'family_members',
            },
        ),
    ]
