# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='admin',
            field=models.OneToOneField(help_text='The user who created and administers this family group', on_delete=django.db.models.deletion.CASCADE, related_name='managed_family_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='family_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.familygroup'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.OneToOneField(help_text='One user can belong to only one family group', on_delete=django.db.models.deletion.CASCADE, related_name='family_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family_group', 'user')},
        ),
    ]
