# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('family', 'Family'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scans_used_this_period', models.PositiveIntegerField(default=0)),
                ('scans_limit', models.PositiveIntegerField(default=10, help_text='Scans allowed per billing period (0 = unlimited)')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('none', 'None')], default='none', max_length=20)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
                ('payment_failure_count', models.PositiveIntegerField(default=0)),
                ('enterprise_seats', models.PositiveIntegerField(default=0, help_text='Number of enterprise user seats')),
                ('enterprise_domain', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
    ]
