# Generated by Django 5.1.4 on 2026-06-07 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('gateway', models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay')], db_index=True, max_length=20)),
                ('payment_type', models.CharField(choices=[('subscription_new', 'New Subscription'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_upgrade', 'Plan Upgrade'), ('refund', 'Refund')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=25)),
                ('amount', models.PositiveBigIntegerField(help_text='Amount in smallest currency unit (e.g., paise for INR, cents for USD)')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('amount_refunded', models.PositiveBigIntegerField(default=0)),
                ('gateway_payment_id', models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent ID or Razorpay payment_id', max_length=255)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Razorpay order_id or Stripe checkout session ID', max_length=255)),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=255)),
                ('payment_method_type', models.CharField(blank=True, choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet')], max_length=20)),
                ('payment_method_last4', models.CharField(blank=True, max_length=4)),
                ('payment_method_brand', models.CharField(blank=True, max_length=20)),
                ('gateway_response', models.JSONField(default=dict, help_text='Full webhook payload from payment gateway')),
                ('webhook_event_id', models.CharField(blank=True, help_text='Gateway webhook event ID for idempotency', max_length=255, null=True, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
