# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft deletion timestamp. NULL means active.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Email Verification')], db_index=True, default='pending_verification', max_length=30)),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('family_admin', 'Family Admin'), ('family_member', 'Family Member'), ('enterprise', 'Enterprise')], default='individual', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, help_text='AI-calculated safety score (0-100)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_preferences', models.JSONField(default=dict, help_text='User notification channel preferences')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('provider', models.CharField(choices=[('email', 'Email & Password'), ('google', 'Google OAuth2'), ('apple', 'Apple Sign-In'), ('phone', 'Phone OTP')], max_length=20)),
                ('provider_uid', models.CharField(blank=True, help_text='User ID from OAuth provider (e.g., Google sub)', max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=512, null=True)),
                ('token_type', models.CharField(blank=True, choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('phone_otp', 'Phone OTP'), ('invite', 'Family Invite')], max_length=30, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the primary authentication method for this user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Auth',
                'verbose_name_plural': 'User Auth Records',
                'db_table': 'user_auth',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('device_id', models.CharField(db_index=True, help_text='Client-generated device fingerprint', max_length=255)),
                ('device_name', models.CharField(blank=True, help_text="Human-readable device name (e.g., 'iPhone 15 Pro')", max_length=100)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=20)),
                ('os_info', models.CharField(blank=True, max_length=100)),
                ('browser_info', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=50)),
                ('jwt_jti', models.CharField(db_index=True, help_text='JWT JTI claim — links this session to a specific token', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'account_status'], name='users_email_3e2f80_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type', 'created_at'], name='users_account_0ff9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='userauth',
            index=models.Index(fields=['token', 'token_type'], name='user_auth_token_777c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userauth',
            index=models.Index(fields=['provider', 'provider_uid'], name='user_auth_provide_374dfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userauth',
            unique_together={('user', 'provider')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['jwt_jti'], name='user_sessio_jwt_jti_7513c1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='user_sessio_expires_66ae96_idx'),
        ),
    ]
