import { PricingPlan } from '@/types';

export const pricingPlans: PricingPlan[] = [
  {
    id: 'Free',
    name: 'Free',
    price: 0,
    priceUSD: 0,
    description: 'Basic protection for individuals',
    features: [
      '5 screenshot scans/month',
      'Basic threat detection',
      'Chat with CyberDaddy AI',
      'Email alerts',
    ],
    highlighted: false,
    maxMembers: 1,
  },
  {
    id: 'Pro',
    name: 'Pro',
    price: 299,
    priceUSD: 3.59,
    description: 'Advanced protection for power users',
    features: [
      'Unlimited screenshot scans',
      'Advanced AI threat analysis',
      'Risk score reports',
      'Priority support',
      'Detailed threat explanations',
      'Scan history (90 days)',
    ],
    highlighted: false,
    maxMembers: 1,
  },
  {
    id: 'Family',
    name: 'Family',
    price: 599,
    priceUSD: 7.19,
    description: 'Complete protection for your whole family',
    features: [
      'Everything in Pro',
      'Up to 10 family members',
      'Family safety dashboard',
      'Shared threat alerts',
      'Parental controls',
      'Family safety score',
      'Dedicated family support',
    ],
    highlighted: true,
    badge: 'Most Popular',
    maxMembers: 10,
  },
  {
    id: 'Enterprise',
    name: 'Enterprise',
    price: 2999,
    priceUSD: 35.99,
    description: 'Enterprise-grade security for organisations',
    features: [
      'Everything in Family',
      'Unlimited members',
      'Custom integrations',
      'API access',
      'Dedicated account manager',
      'SLA guarantee',
      'Custom threat reports',
      'On-premise option',
    ],
    highlighted: false,
    badge: 'Custom',
    maxMembers: Infinity,
  },
];
