# Generated by Django 5.1.4 on 2026-06-07 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('notification_type', models.CharField(choices=[('threat_alert', 'Threat Alert'), ('scan_complete', 'Scan Complete'), ('family_alert', 'Family Alert'), ('weekly_report', 'Weekly Safety Report'), ('subscription', 'Subscription Update'), ('payment', 'Payment Notification'), ('system', 'System Notification'), ('welcome', 'Welcome Message')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Additional data payload (e.g., scan_id, threat_id for deep links)')),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], db_index=True, max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('related_scan_id', models.UUIDField(blank=True, null=True)),
                ('related_threat_id', models.UUIDField(blank=True, null=True)),
                ('related_family_member_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
