# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatScanMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('confidence_score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('match_method', models.CharField(choices=[('keyword', 'Keyword Match'), ('url', 'URL Match'), ('ai', 'AI Pattern Match'), ('regex', 'Regex Match')], max_length=30)),
                ('matched_text', models.TextField(blank=True, help_text='The specific text/URL that triggered this match')),
            ],
            options={
                'verbose_name': 'Threat Scan Match',
                'verbose_name_plural': 'Threat Scan Matches',
                'db_table': 'threat_scan_matches',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('scan_type', models.CharField(choices=[('screenshot', 'Screenshot / Image'), ('sms', 'SMS Text'), ('url', 'URL / Link'), ('email', 'Email Content'), ('phone_number', 'Phone Number')], db_index=True, max_length=20)),
                ('scan_input_text', models.TextField(blank=True, help_text='Raw text input (for SMS, URL, email scans)')),
                ('scan_input_file', models.FileField(blank=True, help_text='Uploaded file (for screenshot scans)', null=True, upload_to='scan_uploads/%Y/%m/')),
                ('scan_input_url', models.URLField(blank=True, help_text='URL being scanned', max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking async processing', max_length=255)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI-calculated risk score 0-100', max_digits=5, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Threat')], db_index=True, max_length=10)),
                ('is_threat', models.BooleanField(db_index=True, default=False)),
                ('ai_response', models.JSONField(blank=True, help_text='Full AI analysis result including reasoning, categories, recommendations', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='Human-readable AI summary for display in app')),
                ('scam_category', models.CharField(blank=True, help_text='Detected scam category (e.g., phishing, investment fraud)', max_length=100)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('family_member', models.ForeignKey(blank=True, help_text='Set if scan was triggered from family monitoring', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scan History',
                'db_table': 'scan_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
