# Generated by Django 5.1.4 on 2026-06-07 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scam_detection', '0001_initial'),
        ('threat_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatscanmatch',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_matches', to='scam_detection.scanhistory'),
        ),
        migrations.AddField(
            model_name='threatscanmatch',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_matches', to='threat_intelligence.threatdatabase'),
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['user', 'scan_type', 'created_at'], name='scan_histor_user_id_e1187a_idx'),
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['user', 'is_threat', 'created_at'], name='scan_histor_user_id_9670e6_idx'),
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['status', 'created_at'], name='scan_histor_status_5ef2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['risk_level'], name='scan_histor_risk_le_9f835d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threatscanmatch',
            unique_together={('scan', 'threat')},
        ),
    ]
